const {SESSION_DURATION_MAX} = require('../constants')
const sessionsDb = require('../persistence/sessions-db')
const sessionCodesRepo = require('../persistence/session-codes-repository')
const guestIdsRepo = require('../persistence/guest-ids-repository')
const validation = require('../validation')

const getFindSession = require('./find-session')
const getFindSessionWithGuests = require('./find-session-with-guests')
const getCreateSession = require('./create-session')
const getConstructGuest = require('./construct-guest')
const getAddGuest = require('./add-guest')
const getAdmitGuest = require('./admit-guest')
const getUpdateState = require('./update-state')
const getViewState = require('./view-state')
const getVerifyFile = require('./verify-file')
const getElevateGuest = require('./elevate-guest')
const getKickGuest = require('./kick-guest')
const getLeaveSession = require('./leave-session')
const getEndSession = require('./end-session')

exports.findSession = () => getFindSession(sessionsDb)
exports.findSessionWithGuests = () => getFindSessionWithGuests(exports.findSession())
exports.constructGuest = () => getConstructGuest(guestIdsRepo, validation)
exports.createSession = () => getCreateSession(sessionsDb, sessionCodesRepo, validation, exports.constructGuest())
exports.addGuest = () => getAddGuest(validation, exports.findSession(), exports.constructGuest())
exports.admitGuest = () => getAdmitGuest(exports.findSessionWithGuests())
exports.updateState = () => getUpdateState(validation, exports.findSessionWithGuests())
exports.viewState = () => getViewState(SESSION_DURATION_MAX, exports.findSessionWithGuests())
exports.verifyFile = () => getVerifyFile(exports.findSessionWithGuests())
exports.elevateGuest = () => getElevateGuest(exports.findSessionWithGuests())
exports.kickGuest = () => getKickGuest(exports.findSessionWithGuests())
exports.endSession = () => getEndSession(sessionsDb)
exports.leaveSession = () => getLeaveSession(exports.findSessionWithGuests(), exports.endSession())
